<?php

namespace Web\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormRepository extends EntityRepository
{
    public function countNonLu()
    {
        $qb = $this->createQueryBuilder('u');
        return $qb
            ->select('count(u.id)')
            ->where('u.etat = 0')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function GetForm($form){
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.type = (:form)')
            ->setParameter('form',$form);
        return $qb->getQuery()->getResult();
    }

    public function setVu($id){
        $queryBuilder = $this->createQueryBuilder('u');
        $queryBuilder
            ->update('WebAdminBundle:Formu', 'u')
            ->set('u.etat', 1)
            ->where($queryBuilder->expr()->eq('u.id', ':id'))
            ->setParameter('id',$id);
        return $queryBuilder->getQuery()->getResult();
    }

    public function setLu(){
        $queryBuilder = $this->createQueryBuilder('u');
        $queryBuilder
            ->update('WebAdminBundle:Formu', 'u')
            ->set('u.etat', 1)
            ->where('u.etat = 0');
        return $queryBuilder->getQuery()->getResult();
    }


    public function setrependu($id){
        $queryBuilder = $this->createQueryBuilder('u');
        $queryBuilder
            ->update('WebAdminBundle:Formu', 'u')
            ->set('u.etat', 2)
            ->where($queryBuilder->expr()->eq('u.id', ':id'))
            ->setParameter('id',$id);
        return $queryBuilder->getQuery()->getResult();
    }
}
