<?php

namespace Web\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterRepository extends EntityRepository
{

    public function getEmail(){
        $qb = $this->createQueryBuilder('u')
            ->select('u.emailNoti');
        return $qb->getQuery()->getResult();
    }

    public function findSocial(){
        $qb = $this->createQueryBuilder('u')
            ->select('u.SocialNetwork');
        return $qb->getQuery()->getResult();
    }

    public function findFooter(){
        $qb = $this->createQueryBuilder('u')
            ->select('u.ftrImpl, u.ftrAdr, u.ftrIntro');
        return $qb->getQuery()->getResult();
    }

    public function findInfo(){
        $qb = $this->createQueryBuilder('u')
            ->select('u.nomSite, u.descSite, u.keyWordSite');
        return $qb->getQuery()->getResult();
    }
}
