<?php

namespace Web\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{

    public function getOne($id){
        $qb = $this->createQueryBuilder('u')
            ->select('u.nom')
            ->where('u.id = (:id)')
            ->setParameter('id','%'.$id.'%');
        return $qb->getQuery()->getResult();
    }

    public function findArray($array){
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.id IN (:array)')
            ->setParameter('array',$array);
        return $qb->getQuery()->getResult();
    }

    public function findlast(){
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->orderBy('u.id', 'DESC')
            ->setMaxResults(10);
        return $qb->getQuery()->getResult();
    }

    public function chercher($ch){
        $qb = $this->createQueryBuilder('u')->select('u');
        $qb->where(
                $qb->expr()->like('u.nom', ':ch')
            )
            ->orWhere(
                $qb->expr()->like('u.code', ':ch')
            )
            ->setParameter('ch','%'.$ch.'%');
        return $qb->getQuery()->getResult();
    }


}
